### ISSUE TITLE
Need better example of use

### ISSUE THREAD

**Issue by mozai** [baniuyao/ZabbixPythonApi#5]
The example of use in the README.md doesn't work.

    from zapi import ZabbixAPI
    ZAPI = ZabbixAPI(url='http://localhost/zabbix', user=UNAME, password=PWORD)
    ZAPI.login()
 
    Traceback (most recent call last):
      File "zapi_example.py", line 8, in <module>
        ZAPI.login()
      File "./zapi.py", line 50, in login
        raise ZabbixAPIException(e)
    zapi.ZabbixAPIException: The "user.login" method must be called without the "auth" parameter.

I'm not passing any parameters to the .login() method.

**Comment by yrjsg** [comment]
Sorry for delay response. It has been fixed.

**Comment by mozai** [comment]
The example in README.md still does not work.

```
zapi.host.get({'hostids':[hostid],'output':'extend'})
Traceback (most recent call last):
  File "zapi_example.py", line 18, in <module>
    zapi.host.get({'hostids':[hostid],'output':'extend'})
  File "/root/zabbix_api/zapi.py", line 43, in __getattr__
    raise ZabbixAPIException('No such API object: %s' % name)
zapi.ZabbixAPIException: No such API object: host

print zapi.getHostByHostid(hostid)
Traceback (most recent call last):
  File "zapi_example.py", line 20, in <module>
    print zapi.getHostByHostid(hostid)
  File "/root/zabbix_api/zapi.py", line 43, in __getattr__
    raise ZabbixAPIException('No such API object: %s' % name)
zapi.ZabbixAPIException: No such API object: getHostByHostid
```

Using Python 2.7.6 and Zabbix 2.4.5
